#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdchar driver..."
        # Calls the utility script that handles insmod and mknod
        /usr/bin/aesdchar_load
        ;;
    stop)
        echo "Stopping aesdchar driver..."
        # Calls the utility script that handles rmmod and cleans up /dev
        /usr/bin/aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0